# Generated by Django 4.1.1 on 2024-04-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_purchaseorder_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalperformance',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='is_deleted',
        ),
    ]
